### ISSUE TITLE
Update driver's experience on check-in

### ISSUE THREAD

**Issue by ro31337** [ro31337/libretaxi#404]
Introduce experience for drivers. Basically, experience is something you can earn by using application. Experience updates on checking-in and incremented by the following rules:

* Rounded to hour epoch time `Math.round((new Date()).getTime() / (60 * 1000))`, so this value is unique for every hour.

So that every hour we'll have have a unique hash. And theoretically, driver can't have experience incremented by more than 24 in a day.

When you check-in and hash is not used, you get `+1` to your `experience` (it's enough to keep previous hash in state so we can compare current to the the previous one for this specific user).

In this story just introduce `UpdateExperienceResponse` and `UpdateExperienceResponseHandler`, so we'll get the value incremented. In the next story we'll notify passengers with `experience` value.

With `experience` value passengers will be able to distinguish between unexperienced/suspicious drivers and experienced/less-suspicious.

**Comment by ericfont** [comment]
Well I think in general needs a reputation system.   Experience could be one part of a driver's reputation.  But mainly want a reputation score that the driver isn't likely to commit a crime on you.  So I think the passenger needs to be able to rate the driver.  But also need reputation for passengers, so drivers can pick passenger who will likely follow through with ride and pay their stated amount.  In keeping with the p2p nature, maybe could have all these different stats stored, so users can make most informed decision based on how they value each stat.

**Comment by ericfont** [comment]
For a reputation system, I'm thinking it might be simpliest to interface with OpenBazaar's decentralized reputation system: http://www.slideshare.net/drwasho/openbazaar-ratings-reviews-and-reputation

Integrating with OpenBazaar could also take care of issue #429

**Comment by ericfont** [comment]
also I want to warn that when making any experience or reputation, they can be easily abused, especially when there is no cost.  For example, the OP's experience system could be easily abused by checking in every hour without actually handling any rides.  And even a system like my first comment could be abused by creating fake accounts and use those fake accounts to falsely report imaginary rides to boost the score, even though no real rides took place.

One solution might involve users optionally linking their LibreTaxi id to a real world identity somehow, such as their driver's license number.  But I would want that to be optional and privacy preserving, to protect users who might get in trouble for ride sharing.

I realize reputation is a somewhat complicated problem (and considering the open-source nature, of course anyone is free to fork and experiment with different methods to see what works best).

**Comment by rocketinventor** [comment]
I think the balance of safety vs privacy will indeed turn out to be quite tricky.

For example, if we are using a blockchain, then all information is public. Requiring license plate numbers and real names add safety in case this information is needed but, leaves it exposed to fraudsters. If a hashing system is used (input license plate number and the hash is stored to a blockchain) then privacy and consistent identity are preserved but, it is impossible to retrieve this information if there is a need for it.

> One alternative might involve users optionally linking their LibreTaxi id to a real world identity somehow, such as their driver's license number. But I would want that to be optional and privacy preserving, to protect users who might get in trouble for ride sharing.

One idea that I have is that **Driver and Rider info that is not immediately public (i.e. real names, license plate numbers, etc.) could be stored in a database (or blockchain) in encrypted form using public-private key cryptography**. When a ride is ordered, the public keys for this info would be traded so that the driver and rider can decrypt (but not tamper with) each other's info. If, any of this info needed to be shared with authorities, there would be no problem. Privacy would also be preserved. This would be similar to booking an Uber and getting this info in the app _after_ it is ordered.

To supplement this, a report system could be used: If multiple riders report that certain personal info is (deliberately) wrong (recorded using the same private key), then the (peer checked and presumably more accurate) info for a person could be shown instead.

The problem with verifying identity is that there is no P2P way to do this. Also, background checks are important but cost money, how will these costs be covered.

>Any experience or reputation system can be easily abused, especially when there is no cost
Blockchains like bitcoin allow storing bits of data in the blockchain by using bogus transactions but there will be a fixed costs. This cost is very small but, it should help. The cost per "transaction" could be **increased** by adding arbitrary amounts of data to what is "stored" in the blockchain.

**Comment by ericfont** [comment]
Yes, I advocate for a public-private key cryptography system for private info.  And yes the bitcoin transaction fee would disincentivize a lot of abuse of the reputation system.

**Comment by ro31337** [comment]
Not important or not current priority at the moment. Closing till the better time.
