### ISSUE TITLE
Statement on Telegram's privacy is exaggerated

### ISSUE THREAD

**Issue by stragu** [ro31337/libretaxi#451]
The following statement on the website:

"(...) Telegram app, most secured and fastest messenger in the world."

… is an exaggeration, as it is not end-to-end encrypted by default, and as speed is difficult to test. Even if the statement was backed up by references, it is impossible to compare all existing messaging apps, and something that is true now will probably be wrong the following week as it is an ever-changing landscape.

I think that such an easily-debunkable statement decridibilises the project.

Could something less subjective be used?

**Comment by ericfont** [comment]
Agree %100.  Not only does it weaken the credibility of the project, I also felt hesitant to recommend my friends use LibreTaxi because I feel irresponsible by recommending a product which is putting out this false info.  The statement should just end with "(...) Telegram app." with a period right there.  Actually I believe this issue should have been on the https://github.com/ro31337/libretaxi-www repo instead.

In the future I hope that LibreTaxi could utilize a fully end-to-end encrypted system.  Maybe one day Signal will support bots (a quick google search doesn't reveal any info, although I did find https://github.com/AsamK/signal-cli which uses a patched version of libsignal that supports registering for the websocket support and provisioning as a slave device...I would think that would be enough for a LibreTaxi bot).

**Comment by ericfont** [comment]
I made a PR https://github.com/ro31337/libretaxi-www/pull/16 to remove the phrase "most secured and fastest messenger in the world" (but I could only do this edit for some languages.)

I also made a PR https://github.com/ro31337/libretaxi-www/pull/14 to remove the superlative "absolute minimum tracking" and instead use "little tracking" because: The first problem is that you are using Telegram, but you could use end-to-end encrypted to your bot's server to achieve minimal tracking. The second problem is that you are sending addresses to Google Maps for generating thumbnails, but google can associate address requests with users and therefore make inferences about where you are going. If instead wanted to avoid tracking, then your server could download OpenStreetMap database and generate the thumbnails without performing an external request.

**Comment by ro31337** [comment]
Fixed, thanks a lot for that! Let me know if issue can be closed. Thank you.

**Comment by stragu** [comment]
Looks good to me, closing it now. Thanks!

**Comment by ericfont** [comment]
good for me, thanks!
