### ISSUE TITLE
Escrowed payment to protect Driver and Rider

### ISSUE THREAD

**Issue by rocketinventor** [ro31337/libretaxi#458]
No one wants to pay for a ride and not actually get it. Drivers don't want to drive and not get paid. To remedy this, escrows can be used.  I came up with **a possible method for escrowed up-front payments using blockchain-based payment**.

- Before the ride is paid for, an "escrow" wallet is randomly generated. The public key is given to the Rider and also publicly recorded. The private key is stored privately with a trusted independent third party (i.e. the server). The Rider is encouraged to pay the estimated cost at some point before the driver takes them to their destination.
  - The Rider pays and no longer has access to the funds.
  - The driver _also_ has no ability to access the funds.
  - If costs go over the estimate, the Rider can transfer more funds.
- After both the driver **and** the rider come to an agreement for the total cost the third party, can do one of the following:
  - Hand over the private key for the wallet to whomever the funds belong
  - Transfer all (or partial) funds to appropriate wallets according to what the Driver and Rider agree to.
- If the Rider claims that they didn't get the promised services (i.e. Driver doesn't show up) and the Rider can't produce _any_ evidence (i.e. GPS logs) to dispute the Rider's claim then the Rider gets refunded.
- In a worse case scenario (with conflicting or incomplete evidence and/or claims), no agreement is come to and the funds can be donated to a charitable cause or to cover project costs

**Comment by evannoronha** [comment]
I think the "If the Rider claims that they didn't get the promised services..." section of this issue will be the hardest to address. Since this is built for people living in rural areas it's possible one or both of the parties will not be able to access the platform at their destination. I can't think of a great system that would fit into the current framework though.

Obviously, a rudimentary solution is better than no solution, but this can open loopholes for riders or drivers to break the rules and not pay. Although the communities using this platform may have their own way of self-regulating an issue like this...

**Comment by rocketinventor** [comment]
@evannoronha Rural issues is not something that I considered (but should work once both parties gain internet access if they agree to same amount). If the ride cost is the same as the estimate, only the rider needs internet access.

>this can open loopholes for riders or drivers to break the rules and not pay or deliver

The idea of this system is so _nobody_ can get the money until an agreement is made. If there is a dispute, neither the driver, nor the passenger can get access to the payment (at least until an agreement is come to). Disputes need to be shown as a reputation, though.

>Maybe banning users from the platform after a certain number of mutual disagreements could curb an issue like this.

Banning only helps if the identity can be tied to something, otherwise, they can just create a new account.

**Comment by bertrandfalguiere** [comment]
Hi, great idea @rocketinventor !
To adress the "Dishonest Driver" or "Dishonest Rider" situations, maybe we can log all the GPS logs of both the Driver and the Rider during all the ride duration. 
-If the two people never were next to each other, we've got a DD situation: he never showed up. 
-If the two GPS positions go apart before they reach an area next to the destination the Rider asked for: DD again. 
In these two cases, the Rider should get a refund.

**Comment by ro31337** [comment]
The problem (and also advantage) here is that LibreTaxi has minimal tracking. There is no GPS position until you share your location explicitly (by clicking a button).

**Comment by bertrandfalguiere** [comment]
I see. I can imagine another solution, but a complex-to-implement one.

BEFORE THE RIDE:
When Driver and Rider agree for a ride, each of them generate a private/public key pair, only for this ride. Public keys are sent to escrow for later checks. Escrow only needs to know these two public keys, and the price.
The Rider deposits the money.

DURING THE RIDE:
The phones connect to each other via Bluetooth during the ride.
Every 30 seconds or so, the Driver's phone send a "message" to the Rider's phone basically saying "we're still connected by bluetooth (meaning, we are together) and our current distance to destination is blablabla", signed with its public key. The Rider's phone checks if the distance matches with the one it calculates from its own GPS, then answers a signed "looks good to me" message.
Only the last message is stored on the two phones without communication with the escrow.
If the connection stops, both gets a notification.

AFTER THE RIDE:
If no problem: Rider sends a message to escrow saying "All good". Driver gets paid. If Rider forgets, Driver gets paid 3 hours later.

IF THERE IS A PROBLEM:
1)... the Driver never showed up. Rider claims for refund. The phones never connected so Driver can't prove they meet. After 24h, Rider get its money back.
2)... the Driver goes to a wrong place/stops before reaching destination. Rider claims for refund. Driver can't give a proof that they were together and at the destination. After 24h, Rider get its money back.
3)... the Rider claim for refund, but the ride did occurred. The Driver can send the last message to the escrow, showing that they were together (via Bluetooth), at the destination point, and that the Rider signed the message so it can't be faked by the Driver. The Driver gets paid.


NB: The escrow doesn't know neither identities. It just knows their two public keys and approximate destination. These keys can't be linked to them because their are unique to the ride. 
NB2: The escrow doesn't know the destination. Driver and Rider agree on distance to destination, not on destination itself.

**Comment by bertrandfalguiere** [comment]
Problem is: you need a phone with Bluetooth and it will suck your battery. Maybe it can be optional?

**Comment by ro31337** [comment]
It sounds interesting. It's not possible now, because of limitations of Telegram. But when we'll go away from this platform, I'll definitely give it a thought. It sounds to me as a great concept.

**Comment by rocketinventor** [comment]
I think that there are other issues besides the battery drain from the constant GPS + Bluetooth connection.
For example, security is an issue: When I use Uber, I don't have to worry about security much because I know that my device is only exchanging specific types of data with a trusted server. If there is a P2P Bluetooth connection, there is a lot more risk; the Rider's device has access to the Driver's device and vice-versa.

> the Rider's phone checks if the distance matches with the one it calculates from its own GPS

I'm not sure why this step is needed. Both devices/users should have already established end coordinates. In the future, I'd expect this information to be logged to a public blockchain

What if devices are connected but don't agree on location? What if one device's battery dies? What if they have a device-device / device-GPS connection issues? Will the driver have to make them leave?


> If Rider forgets, Driver gets paid 3 hours later.

What if the ride is longer than 3 hours?


>  each of them generate a private/public key pair

Why does the driver need a key? From what you described there is only a need for the rider to have a key pair so that the driver can prove that the data came from the rider's device. The driver and escrow service only need the drivers public key to check the messages.

**Comment by bertrandfalguiere** [comment]
Yeah, I didn't give so much thoughts, its just a bold idea from a non-developer.

The general idea behind the Bluetooth + double signing was what both people would be able to prove to the Escrow that they did their part if they disagree. 

> I think that there are other issues besides the battery drain from the constant GPS + Bluetooth connection.
For example, security is an issue: When I use Uber, I don't have to worry about security much because I know that my device is only exchanging specific types of data with a trusted server. If there is a P2P Bluetooth connection, there is a lot more risk; the Rider's device has access to the Driver's device and vice-versa.

The Bluetooth might be useless. The idea behind double signing was that the two travelers agree on the current situation so the Escrow can decided what to do if there is a conflict. But if they agree, no need for Bluetooth, you are right.

> the Rider's phone checks if the distance matches with the one it calculates from its own GPS
 
> I'm not sure why this step is needed. Both devices/users should have already established end coordinates. In the future, I'd expect this information to be logged to a public blockchain

This regular check is to avoid one on the traveler to interrupt the trip and claim for its money.
For example, if the Rider leaves the taxi at a STOP sign two streets before the end, (s)he shouldn't be able to claim for a whole refund. With these checks, the Driver can prove that (s)he did his/her part.
And communicate only the distance to destination rather than destination was to protect privacy. If the address is an underground station it's okay, but if it's a psychiatric hospital, a mosque, a LGBT center, or an individual house, the less public information, the better.

> What if devices are connected but don't agree on location? 

We can fall back on the last agreed position, maybe? And they are immediately notified that if they keep on disagreeing, the Driver will be paid for the part of the trip he did (last agreed position).

> What if one device's battery dies?

IDK. Fresh idea: If the Driver's phone is dead, the Rider should say "all good" to the escrow at the end of the trip before leaving the car, and the Driver gets paid. 
If the Rider's phone is dead, he gives to the Driver a code that the app gave him before (unique to the ride), the Driver enters it and it means "all good" to the Driver.
If both die, the Rider give the code to the Driver, and the Driver communicate to the escrow later, when he gets power again.
This means that the app must generate a code for the Rider that he should write down. (Much like the Blablacar system, if you are in a country where it operates).
Both people are notified in advance when one the batteries is dying.

> What if they have a device-device / device-GPS connection issues?

Let's forget the device-device connection, you're probably right: it's useless.
If there is a device-GPS issue: fall back the idea above if the connection don't get restored.

> What if the ride is longer than 3 hours?

It was just a number so the Rider can have time to notify the Escrow if there was a problem. 
And it starts AFTER the end of the trip. 
If the escrow don't know when the trip ended (battery issue, etc), then it should be 24h, or vary this the distance.

> Why does the driver need a key? From what you described there is only a need for the rider to have a key pair so that the driver can prove that the data came from the rider's device. The driver and escrow service only need the RIDER public key to check the messages.

I'm assuming you meant "Rider" in your last sentence.
Yes, you're right.

**Comment by rocketinventor** [comment]
If the rider wants to leave the vehicle early (i.e. to save on cost) they either need to pay for the whole ride or come to an agreement on payment; no complicated system necessary.

Can you provide more details about the blablacar system?

**Comment by bertrandfalguiere** [comment]
https://www.blablacar.co.uk/faq/the-trip-the-booking-code-and-the-payment

Blablacar is a carpooling platform, so the Drivers are the ones who chose the details of the trip. All available trips are searchable by passengers. There are a website and smartphone apps.

Passengers pay upfront Blablacar (AKA the Escrow) as they book, and they receive a 5-letter code. It is unique to them and to the trip. At the end of the trip, each passenger give his code to the Driver. The Driver can then enter them on the website or the app, and get his money. (Passengers can also confirm directly on their app, if they have it.)
If a passenger forgets, the Driver get paid after 2 weeks. (NB: Default behavior is that the Driver eventually gets paid, because people on Blablacar are considerated reliable. They have a reputation to defend since they are not anonymous. They are evaluated during each trip by their passengers, not unlike the AirBnb system. ) 

In our case, most of the confirmations should occur directly in-app, but the code can be the backup plan I talked about.

**Comment by ro31337** [comment]
Not important or not current priority at the moment. Closing till the better time.
