### ISSUE TITLE
How is this "Free" and "Open Source" ?

### ISSUE THREAD

**Issue by SpEcHiDe** [ro31337/libretaxi#497]
According to the definition given by GNU [here](https://www.gnu.org/philosophy/free-sw.en.html), a product is free software only if it satisfies the four fundamental freedoms. 
In my opinion, since the program is only a Telegram bot, it clearly violates freedom1. So I do not think you could call the software a Free and Open Source project.

**Comment by maasencioh** [comment]
Actually it's free because you are allowed to implement it in other projects. It will be violating the freedom if will forbid it.

**Comment by teslasmoustache** [comment]
Yeah, like a FLOSS program that runs on 64bit architecture is not any less free because it can't run on 32bit architecture.

**Comment by teslasmoustache** [comment]
Besides, Telegram front-end is open source. I believe AGPL?

**Comment by ro31337** [comment]
I giving it as much freedoms as I can (or tell me what else do you expect). I think it's not possible to give anyone more freedom that you have at the moment. MIT license even allows you to close your modifications and use it for commercial purposes. Irony is that some GNU licenses (AGPL for example) are also about restricting the freedom. For example, AGPL license wouldn't allow anyone to close modified source code, with AGPL source code should be always published. In LibreTaxi with MIT license there is no such limitation. So do whatever you want - close, open, sell, resell etc.

At the beginning I could make it purely console, by avoiding Telegram, iPhones, Androids. It will be usable, but... for hackers only. The only driver in this app would be Richard Stallman. It was not my goal. My goal was to make app that works, to give a freedom to make your own clones, to give a freedom to start your own company and business, to give a well-written and understandable source code you can modify, to give you plenty of tests so you'll less likely mess it up.

Hopefully with all of that you'll be able to deliver a practical, not theoretical, _value_ for the user. Hopefully, somebody will save money by using this app. Hopefully, app will change industry to the better in some places on this world. Hopefully, you won't to pay $100 for 1 mile ride, because somewhere in India you'll have plenty of drivers around, instead of aggressive taxi unions. Hopefully, Uber one day will cut less from their drivers (I'm sorry, "driver partners").

**Comment by ro31337** [comment]
If you don't have any more questions, I'll close this issue in two weeks from now.

**Comment by mikeres0** [comment]
Pedantic

**Comment by jiriha51** [comment]
I Love Libreraxi

**Comment by ro31337** [comment]
Closing the issue, seems there are no more questions here. Thanks for discussion, everyone!

**Comment by thirdy** [comment]
>  Irony is that some GNU licenses (AGPL for example) are also about restricting the freedom. For example, AGPL license wouldn't allow anyone to close modified source code. With AGPL, source code should be always published.

Depends on how you view ownership. If you believe that allowing people to _not share_ is okay then use MIT license. If you believe that the work done by many (I see many contributions by others) on this project should be made accessible to all persons of the world, then you should use a copy-left license like AGPL.

> I don't care about definitions of freedom from "GNU", or "FOO", or whatever. They define what they define. LibreTaxi is about the real freedom, not a freedom defined by someone.

You are freely able to define your own definition of 'Free Software'.. But I personally would thumbs down this - but ofc - this is just me. It would be nice if you would stop using "Free", and just "Open Source".

**Comment by ro31337** [comment]
Unfortunately word "free" in English is not the same as in Russian, for example, "Free" translated to Russian (and to some other languages) has two meanings: 1) free of charge (бесплатный) 2) has freedom (свободный)

So again, it depends on your vision of word "free".

Also, I think (subjectively) for Uber/Lyft/(other corporations) it will be much better if software remains AGPL. It means less people/(small companies)/entrepreneurs can fully compete with Uber, because they may need to open source software they already have.

However, I'm not sure which license is better.

**Comment by teslasmoustache** [comment]
Get over it.

Restricting someone from making non-free adaptations of free software does not make free software non-free.

Just like making it illegal for me to own slaves does not make me an un-free person.

Tired of this GD argument.

**Comment by ro31337** [comment]
Thanks for discussion, product seems more sustainable now, and it's better to change the license to AGPL v3.

**Comment by apotheon** [comment]
I disagree.  I cannot even touch AGPL code for many open source ("free software") projects because of license incompatibilities.  I think this is a step in the wrong direction, as the AGPL actually does prevent many people from using it in combination with other open source software.

**Comment by ro31337** [comment]
I got older, and don't like AGPLv3 too much. Wanna roll it back to less restrictive MIT, and I don't care too much about libre open source thing.

**Comment by dnk8n** [comment]
The best compromise would be to keep the default license *GPL v* and then allow small businesses to relicense to MIT license for a nominal fee.

That way, they can legally make their non-free adjustments and support the original contributors.

**Comment by apotheon** [comment]
I disagree.  It's best to include a small, lightweight, clear license with maximum protection of all downstream users, rather than impose additional legal maintenance burdens on everyone, especially those who have fewer resources to devote (like independent open source devs).

**Comment by dnk8n** [comment]
How is GPL not helping smaller open-source developers? They can still make money without paying a thing. GPL just insists that they make available upstream their work for the greater community. Surely that helps the open-source devs more.

If you can't handle up-streaming your code, then there should be an option to buy a license that will allow you to do what you want with it.

It's a debatable topic. There is no correct answer. It really is just up to the maintainers to make their mind up. Whatever they choose impacts that instance of the codebase forever. Can't really take it back. Changes only apply to the future, not the past.

If anything I said is not true, I would love to learn more about it. This is just my current understanding.

**Comment by poVoq** [comment]
It would be really nice if there where alternative backends for more Libre services like for example XMPP. I think if Telegram was only one amongst other options everyone would be fine with it.

**Comment by apotheon** [comment]
> How is GPL not helping smaller open-source developers? They can still make money without paying a thing. GPL just insists that they make available upstream their work for the greater community. Surely that helps the open-source devs more.

See above, where I said "impose additional legal maintenance burdens on everyone, especially those who have fewer resources to devote".

> If you can't handle up-streaming your code, then there should be an option to buy a license that will allow you to do what you want with it.

. . . speaking of resources.

**Comment by dnk8n** [comment]
There is no additional legal maintenance burden to anyone happy to upstream.

If you don't have resources why should you be entitled to a closed-sourced version of code you inherit for free?

Software cost money to make. Why should we expect the initial contributors to give us stuff for free so that we can make one useful change and make profits for the entire thing (without sharing to the initial contributors).

**Comment by apotheon** [comment]
> There is no additional legal maintenance burden to anyone happy to upstream.

That's not true.  Have you ever actually read the entire GPL?  If upstream's maintenance of all specific versions of its code you've used go away before a number of years years after the last time you distribute those versions, for instance, you then have to maintain the source yourself for them to request until that period has expired.  Many projects may be deemed to fall under the "must host your own; referring to upstream is not sufficient" category as well.  Handling of license notification is easy to get wrong.  Combining with additionally-licensed works is a subtle art fraught with difficulty for those who do not pay enough attention to the actual terms of licenses to notice things like continuous source hosting requirements beyond the period of (e.g. binary) software distribution.

It may be illegal for you to give away an old CD installer for some Linux distribution, for instance.  Did you know that?  I doubt it, judging by what you said.

> If you don't have resources why should you be entitled to a closed-sourced version of code you inherit for free?

This seems like an argument that only businesses and wealthy people should be able to redistribute it.  Are you aware of the evident implications of how you said that?
