### ISSUE TITLE
Stallman-compatible?

### ISSUE THREAD

**Issue by nukeop** [ro31337/libretaxi#522]
Does this alternative avoid the piecework subcontractor economy issue present in Uber?

Also, here's a quick rundown on bad things in Uber that are not immediately and obviously not present in libretaxi. Most of it is rephrased from RMS' website, wherever applicable:

- > Uber requires passengers to identify themselves, both to order a ride and to pay. 
    - Are anonymous forms of payment allowable? Bitcoin, cash? I can see cash is allowed, what about anonymous digital currencies?

- > It also records where you get the ride and where you go with it. 
    - Is there any form of route recording present, where passengers could be identified and connected to their routes by any third party?

- > Uber plans to snoop on users' locations and contacts all the time. 
    - Is location tracking required for either drivers or passengers?

- >  The Uber app requires running other nonfree software (in the case of Android, Google Play). 
    - Is any non-free software required to run libretaxi? I know Telegram is free software, what about other pieces?

- Can authors of libretaxi exert any kind of pressure (legal or otherwise) on customers or drivers?

- Is there any centralized data storage, or is the system completely distributed?

- Is it possible (I know that's the idea, but is it currently feasible) to summon a taxi, ride, and pay, completely anonymously, start to finish?

And also: have you received any legal (or other) threats from Uber, Lyft, or some middlemen they hire to squash competition?

**Comment by ro31337** [comment]
> What about anonymous digital currencies?

On the way.

> Is there any form of route recording present, where passengers could be identified and connected to their routes by any third party?

Minimal tracking (I wouldn't even call it tracking) is present. It's required so the app remain functional and usable. However, passengers can easily fake their location (with paperclip icon -> location, while providing location). It can be useful when they do not want to provide exact location and wanna pick the taxi N meters away from where they are.

> Is location tracking required for either drivers or passengers?

Passengers/drivers provide their location by request only, location can be faked. There is no "location tracking" without explicit permission. 

> Is any non-free software required to run libretaxi?

Firebase is non-free software (there is free limited plan available for everyone, however). Hopefully will be replaced soon.

> Can authors of libretaxi exert any kind of pressure (legal or otherwise) on customers or drivers?

Theoretically it is possible: "shutting down the service" sounds like "otherwise". When app is not decentralized, it's always possible for any app/service. Forked source code and MIT license kinda mitigates this risk a little bit: it's always possible to kick off a clone based on existing source code.

> Is there any centralized data storage, or is the system completely distributed?

Centralized. Currently there are no fast and decentralized databases available (only very slow and decentralized). Research is running on the technical possibility to run the app on Ethereum.

> Is it possible (I know that's the idea, but is it currently feasible) to summon a taxi, ride, and pay, completely anonymously, start to finish?

Phone number is required for Telegram. However, can be faked for LibreTaxi just by typing a different number (not sure about that, if not - PR should be introduced to allow that). However, PoC CLI transport allows (probably with few minor modifications) to create completely anonymous LibreTaxi instance if required. This PoC instance can be used within certain communities.

> have you received any legal (or other) threats from Uber, Lyft, or some middlemen they hire to squash competition?

There is possibility of some middlemen involvement. However, there is no enough data at the moment to confirm that.

The app is currently Stallman-incompatible.

**Comment by nukeop** [comment]
Great, thanks for the answers. You're doing God's work.

**Comment by ro31337** [comment]
Closing discussion, answers were provided.
