### ISSUE TITLE
Add support for trasporting things

### ISSUE THREAD

**Issue by HostFat** [ro31337/libretaxi#546]
I think that it should be easy to make Libretaxi being able to support also transporting things, and not only people.

**Comment by randyj63** [comment]
I second that
I own meandatruck.com if someone wants to partner up and get something going

**Comment by MakeHorizont** [comment]
May be [pacifics](pacifics.org/)
[bitboost](http://www.bitboost.net/meet-our-new-partner-passlflix/?utm_source=Twitter&utm_campaign=partnership%20PassLfix)

or theory variant [Lelantos: A Blockchain-based Anonymous Physical
Delivery System
](https://eprint.iacr.org/2017/465.pdf)

**Comment by ro31337** [comment]
That's all very interesting. It would be nice to have the same libre platform for delivery. Should we ICO this? :)

**Comment by MakeHorizont** [comment]
Слушай, я думаю, что это было бы чрезвычайно круто, 

но на данный момент нужно максимально реализовать продакшн, плюшки можно и позже навешать..

максимально реализовать продакшн* - закрыть все возможные баги, дыры и бреши
чтобы не дать заспамить приложение, ибо я уверен, что такие попытки будут (вполне возможно, что по заказу UBER, яндекс, Gett и прочих)
---
Look, I think it would be extremely cool,

But at the moment you need to maximize the realization of production, you can hang some buns later ..

Maximize the realization of production * - close all possible bugs, holes and gaps
So I do not want to spam the application, because I'm sure that such attempts will (it is possible that by order of UBER, Yandex, Gett and others)

**Comment by MakeHorizont** [comment]
Что касается ICO - то да, если провести ICO качественно (качественные реклама/ сайт / распределение токенов) то да, тем более это уже полноценно работающая программа, а не теоретическое фуфло, которое на ico обычно загоняют за миллионы баксов..

**Comment by ro31337** [comment]
@MakeHorizont thanks for your thoughts. I'll keep speaking English if you don't mind, so others will get better understanding (it's okay for you to use another language).

Could you please elaborate more on "распределение токенов" and what do you mean by that? Also, feel free to share your thoughts about the token, and what it should represent in your opinion?

Thanks!

**Comment by MakeHorizont** [comment]
Обычно ICO как и другие версии краудфандинга подразумевает получение "доли" от проекта
это могут быть: 
-официальная благодарность, 
-скидки, 
-материальные вещи (мерч) 
- прочее..

когда люди вкладывают валюту в ICO они обычно получают токены (активы) проекта..

.. которыми они в будущем имеют возможность либо:
- воспользоваться
- продать на бирже (если токены там торгуются)
- хранить и голосовать ими (если такое предусмаривается)

но по факту всё вышеперечисленное не совсем нужно твоему крутому проекту, можно просто собрать денег на проект..

---

Usually ICO, like other versions of crowdfunding, implies getting a "share" from the project
it can be:
-Official thanks,
- a discount,
-Material things (measures)
- Other ..

When people invest in ICO, they usually get project tokens (assets).

.. which they in the future have the opportunity either:
- take advantage of
- sell on the stock exchange (if the tokens are traded there)
- keep and vote by them (if such is foreseen)

But in fact all of the above does not really need your steep project, you can just collect money for the project ..



[Arcade City: Decentralized, Blockchain-Based Answer to Uber](https://www.facebook.com/ArcadeCityHall/)

**Comment by ro31337** [comment]
Not important or not current priority at the moment. Closing till the better time.
