### ISSUE TITLE
Feature request: Driver count near me

### ISSUE THREAD

**Issue by mattiasaxell** [ro31337/libretaxi#609]
Feature request: A potential user (ping @peterk ) would like to see a "Driver Count Near Me"-feature.

From user flow perspective I can imagine it would be nice to be able to see amount of checked-in drivers close by at two places using LibreTaxi bot:

    When user is considering to search for a ride
    When continously having search activated

Just ideas I came up with on the fly.

**Comment by ro31337** [comment]
Maybe it's cool, but it will prevent users from using the app. Having the number of drivers disclose the coverage. Users will have info about the number of drivers, and if it's zero, they will be less likely to use the app in the future. If it's unknown, they can try again later. Closing, mostly because of other more important issues, don't wanna waste resources on this. Thanks for understanding
