### ISSUE TITLE
[Feature Request for Freedom] openstreet map instead of google map

### ISSUE THREAD

**Issue by kirantpatil** [ro31337/libretaxi#632]
Hi,

It is better to use Openstreet map instead of google map

Let's make Openstreet map as default (Can we use [osmbot](https://github.com/Xevib/osmbot) for it ?).

So that we can help and support openstreet map project and also [opentraffic](http://opentraffic.io/) project.

Thanks.

**Comment by ro31337** [comment]
What do you mean by saying "use Openstreetmap"? Where exactly in the app you want to replace it? Please provide more info. Thanks

**Comment by kirantpatil** [comment]
Right now the Driver location and Passenger location are using google map as shown below.

![screenshot_20170910-001852](https://user-images.githubusercontent.com/1178055/30242936-e0c347b0-958f-11e7-9f25-4e74164d5181.png)

**Comment by ro31337** [comment]
Yea, this is something out of our control, unfortunately. It's Telegram feature. Once we have the native app, we can easily get rid of it.

**Comment by kirantpatil** [comment]
Are we planning to come up with native app ? We are not right ?

My only concern with google maps is that they may discontinue the service any time.

**Comment by ro31337** [comment]
Dependencies are always bad, I agree. We have plans for the native app. I do whatever I can to deliver this app. Most of this work is not visible to the public at the moment, though. One day, sooner or later, we'll have the app.

**Comment by kirantpatil** [comment]
IMHO, it is better to release now, even if it is not in working state, so that we can have a look at it and start working on it.

Why I am saying this is, I am preparing some students to contribute for this project. I have promised them that they will be working on this prestigious project, which is used around the world. They should not feel bad that their contribution is used by no one, if every one start switching to native app.

Does native app involves interacting with web app where database is maintained centrally and what it would be ?

For web server, in my opinion it is better to go with Rails 5 and Postgresql DB.

What is your opinion ?

Thanks.

**Comment by kirantpatil** [comment]
How about creating hybrid app using RAILS 5 + [Turbolinks](https://github.com/turbolinks/turbolinks) ?

Ex: [Basecamp](https://m.signalvnoise.com/the-majestic-monolith-29166d022228)

**Comment by ro31337** [comment]
Technology choice won't help here too much (unfortunately). It's all about available resources.

**Comment by ro31337** [comment]
Well, the answer to your questions is... this app is not very easy to build :) Thousands of engineers are working on Uber/Lyft. LibreTaxi for Telegram is the first step. We're going to develop this platform no matter what (even when we'll have native app one day). Chat bot is nice, some people even prefer chat bots over native apps. There is a lot of room for imagination. For example, imagine that you speak to Siri instead of using Uber. "Hey Siri, I need a taxi". And LibreTaxi is the same concept.

So chat bots are important, native apps are important as well, but it's little bit different vector. We're definitely not going to abandon chat bot platform over the native app. They will perfectly work together.

**Comment by ro31337** [comment]
Since it's something out of control at the moment (Telegram feature), and we have no mobile app, keeping this story open makes not too much sense (IMO). I'll reopen the story if you want when we'll have native mobile app in development.
