### ISSUE TITLE
Add option to register drivers and passengers

### ISSUE THREAD

**Issue by s33d3r** [ro31337/libretaxi#687]
To improve security for passengers and drivers and allow use in private environments there should be an option to let drivers and passengers register and allow the bot admin to aprove those registrations.
This should fix in grand part the security issues and make possible to create libretaxi instances in different communities.
For decentralization of power there could be an option to the instance users to approve other users registration. Less secure but also a possibility.
I don't have the resources now but plan to make recurring donations in the future. Probably when we have any of these feature running it will be possible.
Thanks!!!

**Comment by ro31337** [comment]
1. Decentralization is different concept. Let's skip it for this issue.
2. "grand part the security issues and make possible to create libretaxi instances in different communities." - is there any proof of that? Or it's just your thoughts?
3. "could be an option to the instance users to approve other users" -> in other words, functionality is defined. We don't know how it should work. If we don't know, I'll close this issue, because it's not ready to work on. And we can discuss details before someone can start working on this story.
