### ISSUE TITLE
Driver availability

### ISSUE THREAD

**Issue by mattcoxonline** [ro31337/libretaxi#695]
One reason that I don't use LibreTaxi is because I have no idea how many drivers are available in my area. If I were to use something like Uber - I will order based on knowing there is at least one available car within the vicinity - you can view them moving about on the map.

I see this has been mentioned a number of times and each time rejected as an improvement to the product: #682 / #609 / #571 

> "Users will have info about the number of drivers, and if it's zero, they will be less likely to use the app in the future. If it's unknown, they can try again later."

Whilst I understand the concern raised in #609: that showing zero drivers puts people off using the service, I'd argue the opposite is true too. Not allowing people to see available drivers puts people off using the service.

This is why [Uber "fakes" the drivers on the map](https://bgr.com/2015/07/28/uber-app-lying-cars-visual-effect/). It's also why [Google Maps has started showing real-time driver locations](https://thenextweb.com/google/2017/01/12/google-maps-will-now-show-ubers-on-directiontellingthingy/). They know that in seeing availability people are more likely to start the ordering process. If you can't see how many drivers they are, you won't want to place an order.

I'd love to be able to query the availability as the first step in the ordering process:

> Which taxi type do you want?

> 🚗Car
> 🛵Scooter / Motorbike
> 🔍**Show available rides**

> Share your location with us, and we'll tell you what's nearby.

> 📍**Share your location**

> Thanks! There are 14 drivers nearby.
> 
> 🚗10 cars
> 🛵4 scooters / motorbikes
> 
> Which taxi type would you like to order?

> 🚗Car
> 🛵Scooter / Motorbike

It would be interesting to show either **total registered drivers in that area**, or **number of drivers active within x period of time**.

**Comment by ro31337** [comment]
> number of drivers active within x period of time.

Unfortunately Telegram doesn't have this feature - live location update (it has, but it's unusable in LibreTaxi - you need to do multiple actions to send location, nobody will do that). So drivers need to be checked in.

> Thanks! Unfortunately, there are 0 drivers nearby.

There is a problem here. Currently, even if there are 0 drivers, and somebody is checking in in the area, you'll get notification.

Compare:

Current:
Imagine the driver who checked-in 50km away. You're looking for rides, there are no drivers around, but you don't know it. You search for drivers, it takes 20 mins now. After 10 minutes driver who was checked-in 50km away and couple of hours ago checking-in in your area. And gets notification about you waiting. Driver will reply and you'll get connected.

Your suggestion:
Imagine the driver who checked-in 50km away. You're looking for rides, there are no drivers around, and you know it, you're getting "Unfortunately, there are 0 drivers nearby". After 10 minutes driver who was checked-in 50km away and couple of hours ago checking-in in your area. And driver is not getting any notifications about you were there looking for rides, most probably you'll use other ways of transportation. Driver will never reply and you'll never get connected.

With live location feature it can be possible to do.

(One possible solution is stand-alone app. It will require philanthropic funding of LibreTaxi 501c3, because it's not easy as it seems. I'm talking to people, but IRS paperwork is not yet finished, nobody wants to talk to me without that. IRS had raised some questions (see patreon post), and I replied back, and the outcome is not predictable at the moment, because I had no funds to file paperwork with a lawyer - I did it by myself)

**Comment by agajdosi** [comment]
@ro31337 Is there a way how to get information about how many drivers/passengers used LibreTaxi in last day/week/month? I would like to start using the app for sharing the rides over around the city to lower the CO2 print, however I have no idea if there is anybody around using it. If it is not possible now to show real-time data, then maybe wider time window statistics could be a compromise which could help to get some users into using LT?

BTW big +1 for the real time support. That is the functionality I look for as I want to share the rides not really for money, but just give someone a lift when we have similar destinations. Is there an issue for this RT support?

**Comment by ro31337** [comment]
@agajdosi yes, there is an issue. Look my explanation above (if I understand your "real time support" correctly). I can look up specific city, but you shouldn't rely on that. You need to spread the word by yourself. LT is technical and social platform. Nobody is investing millions in spreading the word, we rely on you ;) For example, install the app, share on local boards (reddit, facebook), post stickers in cafes. This should do the trick, or at least it can be the first step.

**Comment by avocadoras** [comment]
> One possible solution is stand-alone app
has there been any progress on this? I like the idea but using the app with Telegram is confusing
