### ISSUE TITLE
Replace Google Maps API with OSM

### ISSUE THREAD

**Issue by iSasFTW** [ro31337/libretaxi#702]
Would it be possible to replace the Google Maps geocoding API with OpenStreetMap's alternative?
With the new Google Cloud Platform system, the process of getting an API key is more complicated than before: A Cloud Platform project has to be created, and billing has to be set up (even if you are just using the service within the free limits). This makes it significantly more time consuming to set up LibreTaxi for testing. 
Based on what's written in the docs, I'm guessing node-geocoder is used for geocoding. Afaik that project supports OSM's geocoding API, and I'm thinking therefore it wouldn't be that hard to switch to. 
Here are the docs for Nominatim (the geocoding api in question): https://wiki.openstreetmap.org/wiki/Nominatim

**Comment by ro31337** [comment]
Problem with OSM is really bad geocoding. Try to type "ssf bart" (which is understandable to lots of people in some region) when LibreTaxi asks for location or address (you can type address from your phone instead of sending location). Google's geocoder will decode "ssf bart" to "south san francisco bart", and to correct GPS coordinates. While alternative only makes project worse, from the user perspective.

I agree that OSM will be nice for you, me, and Richard Stallman. However, usability is everything in this app. Even in existing form the bar is too high for the average user.

**Comment by iSasFTW** [comment]
@ro31337 Are there any other potential replacements for the Google Maps Platform?

**Comment by ro31337** [comment]
Well, it also depends what "replacement" means. If we are talking about _maps_, it's possible to replace with OSM (in stand-alone, non-telegram app). I wanted to make this app independent of Google Maps in the future (1st version may have dependency). If we're talking about geocoding, there is no too much choice to my understanding at the moment.

**Comment by iSasFTW** [comment]
@ro31337 Ah, that's too bad... Do you have any experience with HERE maps? I'm a bit curious about that one. Also, should this issue be closed?

**Comment by ro31337** [comment]
No, I don't have any experience with HERE maps. Closed this issue

**Comment by kirantpatil** [comment]
We should work out on a plan to support OSM OR ANY freesoftware map solution. Community please feel free to open a new discussion on the same.

**Comment by kirantpatil** [comment]
Why don't we encourage people to use OSM and provide interface reenter geocode appropriate

**Comment by kirantpatil** [comment]
A good tutorial to contribute to OSM.

https://harrywood.co.uk/blog/2018/06/05/space4-openstreetmap-talk/#comment-456639
