### ISSUE TITLE
Setup Vagrant for local development

### ISSUE THREAD

**Issue by swember** [ro31337/libretaxi#708]
Create Vagrant configuration with all needed setup for local development.

**Comment by ro31337** [comment]
Looks good, let's get started. Here what you'll need:

1) create your own branch like `708-vagrant`
2) start doing all work, when commiting use prefix of "#708" for commit messages. For example "#708 Add initial vagrant setup" or "#708 Improve blabla"
3) I recommend looking at https://chris.beams.io/posts/git-commit/ so your commit messages align with other commit messages in this repo
4) When done, push your changes and create PR :) I appreciate if you can create/update docs, so  anyone knows that now you can run things with Vagrant instead of setting it up manually on local machine.

Thanks!
